const PUBLISHER_URL='https://script.google.com/macros/s/AKfycbzavxknADmXnvAhRqcf9areGCRpfAJIZ62v84kqb_hpfgfAWIUbngcCH4B8M9TpkuA-uw/exec';
const DRIVE_API_URL='https://script.google.com/macros/s/AKfycbxY93Vr1Zuij1sIKM7X0sgmyT5ipFnufnYGUrw6DqSAQL8QQYM6juVkRszGf-QdRKMEWQ/exec';
const SECRET_KEY='pd_publish_secret';
let selectedImage=null;

const $=id=>document.getElementById(id);
const val=id=>$(id).value.trim();
const status=m=>{$('status').textContent=m;console.log('[Dispatch]',m)};

$('date').value=new Date().toISOString().slice(0,10);
$('image').addEventListener('change',e=>{const f=e.target.files[0];selectedImage=f||null;if(f){const r=new FileReader();r.onload=()=>{$('imagePreview').src=r.result;$('imagePreview').style.display='block'};r.readAsDataURL(f)}else $('imagePreview').style.display='none'});

function secret(){let s=localStorage.getItem(SECRET_KEY)||'';if(!s){s=prompt('Enter the Pleasure Dispatch publishing key:')||'';s=s.trim();if(s)localStorage.setItem(SECRET_KEY,s)}if(!s)throw Error('Publishing key is required.');return s}
function clean(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function nl(s){return clean(s).replace(/\n\s*\n/g,'</p><p>').replace(/\n/g,'<br>')}
function edition(){const m=val('edition').match(/\d+(?:\.\d+)?/);if(!m)throw Error('Enter an edition number.');return m[0]}
function buildHtml(imageUrl=''){
 const ed=edition(), title=val('title')||'The Pleasure Dispatch';
 const notes=[['Coffee',val('coffee')],['Art',val('art')],['Object',val('object')],['Currently',val('currently')]].filter(x=>x[1]);
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Pleasure Dispatch — No. ${clean(ed)}</title></head><body style="margin:0;background:#303030;color:#f2eee5;font-family:Georgia,serif"><main style="max-width:760px;margin:auto;padding:64px 24px 100px"><div style="font:11px ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase;color:#c9c3b8">THE PLEASURE DISPATCH · NO. ${clean(ed)}</div><h1 style="font-size:clamp(44px,8vw,78px);font-weight:400;line-height:.92;letter-spacing:-.04em;margin:22px 0 10px">${clean(title)}</h1>${val('subtitle')?`<p style="font-size:22px;color:#c9c3b8;margin:0 0 36px">${nl(val('subtitle'))}</p>`:''}<div style="font:11px ui-monospace,monospace;color:#aaa;margin-bottom:50px">${clean(val('date'))}</div>
${val('reflection')?`<section><div style="font:11px ui-monospace,monospace;letter-spacing:.12em;color:#aaa">01 — A REFLECTION</div><div style="font-size:21px;line-height:1.55;margin:14px 0 50px"><p>${nl(val('reflection'))}</p></div></section>`:''}
${(val('workText')||imageUrl)?`<section><div style="font:11px ui-monospace,monospace;letter-spacing:.12em;color:#aaa">02 — THE WORK</div>${imageUrl?`<img src="${imageUrl}" style="display:block;max-width:100%;height:auto;margin:18px 0 24px">`:''}${val('workText')?`<div style="font-size:19px;line-height:1.55"><p>${nl(val('workText'))}</p></div>`:''}<div style="height:50px"></div></section>`:''}
${val('studioText')?`<section><div style="font:11px ui-monospace,monospace;letter-spacing:.12em;color:#aaa">03 — STUDIO NOTES</div><div style="font-size:19px;line-height:1.55;margin:14px 0 50px"><p>${nl(val('studioText'))}</p></div></section>`:''}
${notes.length?`<section><div style="font:11px ui-monospace,monospace;letter-spacing:.12em;color:#aaa">04 — PLEASURE NOTES</div><div style="margin:18px 0 50px">${notes.map(n=>`<p style="font-size:17px;line-height:1.5"><strong>${clean(n[0])}</strong><br>${nl(n[1])}</p>`).join('')}</div></section>`:''}
${val('inviteTitle')||val('inviteText')||val('ctaUrl')?`<section><div style="font:11px ui-monospace,monospace;letter-spacing:.12em;color:#aaa">05 — AN INVITATION</div>${val('inviteTitle')?`<h2 style="font-size:30px;font-weight:400">${clean(val('inviteTitle'))}</h2>`:''}${val('inviteText')?`<div style="font-size:18px;line-height:1.5"><p>${nl(val('inviteText'))}</p></div>`:''}${val('ctaUrl')?`<p><a href="${clean(val('ctaUrl'))}" style="color:#f2eee5">Continue →</a></p>`:''}<div style="height:50px"></div></section>`:''}
${val('question')?`<section style="border-top:1px solid #666;padding-top:24px"><div style="font:11px ui-monospace,monospace;letter-spacing:.12em;color:#aaa">06 — A QUESTION</div><p style="font-size:28px;line-height:1.25">${nl(val('question'))}</p></section>`:''}
<footer style="border-top:1px solid #666;margin-top:70px;padding-top:18px;font:10px ui-monospace,monospace;color:#999">FLRSGLOBAL · THE PLEASURE DISPATCH</footer></main></body></html>`;
}

function preview(){const html=buildHtml(selectedImage?$('imagePreview').src:'');$('preview').innerHTML=new DOMParser().parseFromString(html,'text/html').body.innerHTML;$('previewCard').style.display='block';$('previewCard').scrollIntoView({behavior:'smooth'});status('Preview ready')}

async function uploadDrive(dataUrl,fileName,mimeType){const comma=dataUrl.indexOf(',');const body=JSON.stringify({action:'upload',fileName:fileName,mimeType:mimeType,fileContent:comma>=0?dataUrl.slice(comma+1):dataUrl});const r=await fetch(DRIVE_API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body});if(!r.ok)throw Error('Google Drive returned HTTP '+r.status+'.');const j=await r.json();if(j.status!=='created')throw Error(j.message||'Google Drive did not create the file.');return j}
async function uploadImage(){if(!selectedImage)return '';status('Uploading image…');const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(selectedImage)});const result=await uploadDrive(data,'PD_'+edition()+'_'+Date.now()+'_'+selectedImage.name,'image/jpeg');return result.imageUrl||('https://drive.google.com/thumbnail?id='+encodeURIComponent(result.fileId)+'&sz=w1800')}

async function savePdf(){if(!$('savePdf').checked)return null;if(!window.jspdf)return null;status('Creating archival PDF…');const doc=new jspdf.jsPDF({unit:'pt',format:'letter'});let y=60;const W=doc.internal.pageSize.getWidth(),M=52;
 doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('THE PLEASURE DISPATCH · NO. '+edition(),M,y);y+=30;doc.setFont('times','normal');doc.setFontSize(30);const title=doc.splitTextToSize(val('title')||'The Pleasure Dispatch',W-M*2);doc.text(title,M,y);y+=title.length*34+12;doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text(val('date'),M,y);y+=32;
 const sections=[['01 — A REFLECTION',val('reflection')],['02 — THE WORK',val('workText')],['03 — STUDIO NOTES',val('studioText')],['04 — PLEASURE NOTES',[['Coffee',val('coffee')],['Art',val('art')],['Object',val('object')],['Currently',val('currently')]].filter(x=>x[1]).map(x=>x[0]+': '+x[1]).join('\n')],['05 — AN INVITATION',[val('inviteTitle'),val('inviteText')].filter(Boolean).join('\n')],['06 — A QUESTION',val('question')]].filter(x=>x[1]);
 for(const [head,text] of sections){if(y>710){doc.addPage();y=55}doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(head,M,y);y+=18;doc.setFont('times','normal');doc.setFontSize(13);const lines=doc.splitTextToSize(String(text),W-M*2);for(const line of lines){if(y>735){doc.addPage();y=55}doc.text(line,M,y);y+=18}y+=20}
 doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('FLRSGLOBAL · The Pleasure Dispatch',M,760);const blob=doc.output('datauristring');return uploadDrive(blob,'The_Pleasure_Dispatch_No_'+edition()+'.pdf','application/pdf')}

async function publish(){const b=$('publishBtn');b.disabled=true;$('result').style.display='none';try{const key=secret();let imageUrl='';if(selectedImage)imageUrl=await uploadImage();const html=buildHtml(imageUrl);status('Publishing Dispatch…');const payload={action:'publish',secret:key,edition:edition(),editionLabel:'No. '+edition(),date:val('date')||new Date().toISOString().slice(0,10),title:val('title')||'The Pleasure Dispatch',subtitle:val('subtitle'),subject:'The Pleasure Dispatch — No. '+edition()+': '+(val('title')||'A Note on Pleasure'),reflection:val('reflection'),html:html,searchText:[val('title'),val('subtitle'),val('reflection'),val('workText'),val('studioText'),val('inviteTitle'),val('inviteText'),val('question')].filter(Boolean).join(' ')};
 const r=await fetch(PUBLISHER_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});if(!r.ok)throw Error('Publisher returned HTTP '+r.status+'.');const j=await r.json();if(j.success===false||j.status==='error')throw Error(j.error||j.message||'Publishing failed.');let pdf=null;try{pdf=await savePdf()}catch(e){console.warn(e);status('Published; PDF archive failed.')}const url=j.url||j.publicUrl||j.dispatchUrl||'';$('result').innerHTML='<strong>✓ Dispatch published.</strong>'+ (url?'<br><a href="'+url+'" target="_blank" rel="noopener">Open published Dispatch →</a>':'')+(pdf?'<br><span>✓ Archival PDF saved to Drive.</span>':'');$('result').style.display='block';status('Published successfully');}catch(e){console.error(e);$('result').innerHTML='<span class="danger">Publishing failed: '+clean(e.message)+'</span>';$('result').style.display='block';status('Publish failed')}finally{b.disabled=false}}

$('previewBtn').addEventListener('click',preview);$('publishBtn').addEventListener('click',publish);
